FROM openjdk:17-jdk-alpine
LABEL authors="danilmaksimov"
COPY target/realtime-service-0.0.1-SNAPSHOT.jar realtime-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "realtime-service-0.0.1-SNAPSHOT.jar"]