services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - frontend-builded-files:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d:ro

  build-frontend:
    build: .
    volumes:
      - frontend-builded-files:/app/dist

volumes:
  frontend-builded-files:
