services:
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: lister
      POSTGRES_PASSWORD: HuPToNTK3
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: danilovmaximov@gmail.com
        PGADMIN_DEFAULT_PASSWORD: HuPToNTK3
      ports:
        - "5050:80"

  realtime-service:
    container_name: realtime-service
    build:
      context: realtime-service
      dockerfile: Dockerfile
    image: lister-realtime-service:latest
    ports:
      - "9000:9000"
    
volumes:
  pgdata:
