name: lister

services:
  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: lister
      POSTGRES_PASSWORD: HuPToNTK3
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
      - ./database/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lister.com
      PGADMIN_DEFAULT_PASSWORD: HuPToNTK3
    ports:
      - "5050:80"
    volumes:
      - ./database/pgadmin:/var/lib/pgadmin

  tasks-service:
    container_name: tasks-service
    build: ./tasks-service
    ports:
      - "9052:9052"

  api-gateway:
    container_name: api-gateway
    build: ./lister-api-gateway
    ports:
      - "9050:9050"

  eureka-server:
    container_name: eureka-server
    build: ./lister-eureka
    ports:
      - "9001:9001"

  # web-server:
  #   container_name: web-server
  #   build: ./frontend
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d:ro
